"""empty message

Revision ID: 1850c8002412
Revises: 26a09049bba4
Create Date: 2015-03-02 00:25:41.373754

"""

# revision identifiers, used by Alembic.
revision = '1850c8002412'
down_revision = '26a09049bba4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_album',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_table('photo',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['photo_album.aid'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    op.drop_table('photo_album')
    ### end Alembic commands ###
