"""empty message

Revision ID: 26a09049bba4
Revises: 261a3dfc02bc
Create Date: 2015-03-01 23:32:59.808951

"""

# revision identifiers, used by Alembic.
revision = '26a09049bba4'
down_revision = '261a3dfc02bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_book_entry',
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('post', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('eid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest_book_entry')
    ### end Alembic commands ###
