"""empty message

Revision ID: 400d4b7e2e42
Revises: None
Create Date: 2015-03-01 17:35:36.493947

"""

# revision identifiers, used by Alembic.
revision = '400d4b7e2e42'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum(['bb', 'hotel'], name='accommodation_type_enum'), nullable=False),
    sa.Column('distance', sa.Text(), nullable=False),
    sa.Column('price', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contact_name', sa.Text(), nullable=False),
    sa.Column('contact_telephone', sa.Text(), nullable=True),
    sa.Column('contact_mobile', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.Text(), nullable=True),
    sa.Column('contact_address', sa.Text(), nullable=True),
    sa.Column('contact_website', sa.Text(), nullable=True),
    sa.Column('google_maps_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('aid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accommodation')
    ### end Alembic commands ###
